samples:
    # Specify path to sample layout
    path: 'config/project_files/layout.csv'
    # Choice of samples to process, either list of Sample_names: ['My_sample_1', 'My_sample_2']
    # or to process all samples: 'all'
    selection: 'all'
    # Specify what makes each sample unique (other than Timepoint and Replicate)
    attributes: ['Species', 'Mating_type', 'Fragment']
    # Specify path to file containing the number of mitotic generations for each condition
    generations: 'config/project_files/nbgen.xlsx'
    
codon_table: 'ScerevisiaeTAXID559292_Cocoputs_codon_table.csv'

rc_aims:
    # Specify targeted read count per sample
    exp_rc_per_sample: 3e4
    # Specify target read count per variant
    exp_rc_per_var: 5

filter:
    # Specify read count threshold to label variants with a confidence score
    rc_threshold: 10
